### ISSUE TITLE
The ship does not go down

### ISSUE THREAD

**Issue by aneelabaji** [ahmemon/asteroidAttackScratch#6]
Steps:
"1. Press the up arrow to go upwards
2.Press the down arrow for the ship to go down"

Actual:
By pressing the up arrow the ship goes up and by pressing the down arrow the ship does NOT go down. Infact for the ship to go down the left arrow was used.

Expected:
By pressing the up arrow the ship will go up and by pressing the down arrow the ship will come down inshAllah

**Comment by aneelabaji** [comment]
version 5.2

**Comment by IbrahimAMemon** [comment]
fixed in v5.3

**Comment by aneelabaji** [comment]
Sir the bug is still there as can see the ship does not go down by pressing the down arrow.
