### ISSUE TITLE
bombing asteroids

### ISSUE THREAD

**Issue by aneelabaji** [ahmemon/asteroidAttackScratch#8]
Steps:
"1.Wait for asteroids to be below the ship
2.Press on the b button"

Actual:
All the asteroids did not disappear only the one that was bombed did. Also the screen was flashing yellow when using the bomb

Expected:
All of the asteroids on the screen will disappear , and than a orange bomb animation will appear inshaAllah

**Comment by aneelabaji** [comment]
version 5.2

**Comment by IbrahimAMemon** [comment]
fixed in 5.3.

**Comment by aneelabaji** [comment]
Sir as can see by bombing only one asteroid dies not all, and there is no orange bomb animation that appeared. So bug is still there. please check and sorry for the inconvenience
